#include <stdio.h>

void intro()
{
    printf("\n\n\n\n\n\n\n\n\n\n\n\n\n                                                     _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _");
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n\n\n\n                                               _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _");
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n\n\n\n                                           _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _");
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n\n\n\n                                      _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _");
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n\n\n\n                                  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _");
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n\n\n\n                              _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _");
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n\n\n\n                          _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _");
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n\n\n\n                       | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _");
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n\n\n                       |");
    printf("\n                       | _ _ _ _ _ _ %c _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _", 92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n\n                       |");
    printf("\n                       |            %c", 92);
    printf("\n                       | _ _ _ _ _ _ %c _ _ | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _",92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |");
    printf("\n                       |           %c",92);
    printf("\n                       |            %c      |",92);
    printf("\n                       | _ _ _ _ _   %c _ _ | _ _ _ _ | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _",92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |");
    printf("\n                       |           %c       |",92);
    printf("\n                       |          / %c      |         |",92,92);
    printf("\n                       | _ _ _ _     %c _ _ | _ _ _ _ | _ _ _ _ _ _ %c _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _",92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                     _");
    printf("\n                       |           %c       |         |",92);
    printf("\n                       |          / %c      |         |            %c",92,92,92);
    printf("\n                       | _ _ _   /   %c _   | _ _ _ _ | _ _ _ _ _ _ %c _ _ | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _",92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        _");
    printf("\n                       |           %c       |         |            |",92);
    printf("\n                       |          /_%c      |         |            %c      |",92,92,92);
    printf("\n                       | _ _     /   %c     | _ _ _ _ | _ _ _ _ _ _ %c _ _ | _ _ | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _",92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _");
    printf("\n                       |           %c       |  |      |            |      |",92);
    printf("\n                       |          /_%c      |         |            %c      |     |",92,92,92);
    printf("\n                       | _ _     /   %c     | _ _ _ _ | _ _ _ _ _ _ %c _ _ | _ _ | _ _ _ _ | _ _ _ _ _ _ _ _ _ _ _ _ _ _",92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _       %c",169);
    printf("\n                       |           %c       |  |      |            |      |     |",92);
    printf("\n                       |          /_%c      | -       |-           %c      |     |         |",92,92,92);
    printf("\n                       | _ _     /   %c     | _ _ _ _ | _ _ _ _ | _ %c _ _ | _   | _ _ _ _ | _ _ | _ _ _ _ _ _ _ _ _ _",92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _       %c",169);
    printf("\n                       |           %c       |  |      |            |      |     |%c        |",92,92);
    printf("\n                       |          /_%c      |--       |--       |  %c      |     |         |     |",92,92,92);
    printf("\n                       | _ _     /   %c     | _ _ _ _ | _ _ _ _ | _ %c _ _ |     | _ _ _ _ | _ _ | _ _ _ _ _ _ _ _ _  ",92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _       %c               _",169);
    printf("\n                       |           %c       |  |      |         |  |      |     |%c        |     |",92,92);
    printf("\n                       |          /_%c      |--       |--       |  %c      |     | %c       |     |",92,92,92,92);
    printf("\n                       | _ _     /   %c     | _ | _   | _ _ _   | _ %c _   |     | _ _ _ _ | _ _ | _ _ _ _ _ _ _ _    ",92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _       %c              ___",169);
    printf("\n                       |           %c       |  |      |         |  |      |     |%c        |     |",92,92);
    printf("\n                       |          /_%c      |--%c      |--       |  %c      |     | %c       |     |",92,92,92,92,92);
    printf("\n                       | _ _     /   %c     | _ |     | _ _     |   %c     |     | _%c_ _ _  | _ _ | _ | _ _ _ _ _      ",92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _       %c             _____",169);
    printf("\n                       |           %c       |  |      |         |  |      |     |%c        |     |",92,92);
    printf("\n                       |          /_%c      |--%c      |--       |  %c      |     | %c       |     |   |",92,92,92,92,92);
    printf("\n                       | _ _     /   %c     | _ |     |_ _      |   %c     |     | _%c| _ _ | _   | _ | _ _ _ _        ",92,92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _       %c             _____",169);
    printf("\n                       |           %c       |  |      |         |  |      |     |%c        |     |   |",92,92);
    printf("\n                       |          /_%c      |--%c      |--       |  %c      |     | %c |     |     |   |",92,92,92,92,92);
    printf("\n                       | _ _     /   %c     | _ |     |_ _      |   %c     |     |  %c| _   |     | _ | _ _ _          ",92,92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _       %c             _____",169);
    printf("\n                       |           %c       |  |      |         |  |      |     |%c  |     |     |   |",92,92);
    printf("\n                       |          /_%c      |--%c      |--       |  %c      |     | %c |     |     | - |",92,92,92,92,92);
    printf("\n                       | _ _     /   %c     | _ |     |_ _      |   %c     |     |  %c|     |     | _ | _ _           ",92,92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _       %c             _____",169);
    printf("\n                       |           %c       |  |      |         |  |      |     |%c  |     |     |   |",92,92);
    printf("\n                       |          /_%c      |--%c      |--       |  %c      |     | %c |     |     |---|",92,92,92,92,92);
    printf("\n                       | _ _     /   %c     | _ |     |_ _      |   %c     |     |  %c|     |     |   | _              ",92,92,92);
    usleep(8000);
    system("cls");
    printf("\n\n\n\n\n\n\n\n\n\n                       |                    __        __         _       %c             _____",169);
    printf("\n                       |           %c       |  |      |         |  |      |     |%c  |     |     |   |",92,92);
    printf("\n                       |          /_%c      |--%c      |--       |  %c      |     | %c |     |     |---|",92,92,92,92,92);
    printf("\n                       | _ _     /   %c     | _ |     |_ _      |   %c     |     |  %c|     |     |   |                ",92,92,92);
    usleep(8000);
    printf("\n\n\n\n\n\n\n\n\n\n                            Presione cualquier tecla para COMENZAR                  ");
    system("pause -> NULL");
    return;
}

